### ISSUE TITLE
내선번호 검색 기능

### ISSUE THREAD

**Issue by yoonsue** [yoonsue/labchat#12]
교내 내선번호 검색 기능 (부서 및 내선번호) 출력해주는 기능 추가

**Comment by yoonsue** [comment]
1. phone 명령어를 띄어쓰기로 구분하기 때문에 deptartment에 띄어쓰기가 있으면 구분하지 못합니다.
2. =가 붙은 항목은 skip을 진행하였지만, 하위 department 앞에 나와야합니다.
3. department이름이 일부여도 찾을 수 있게 구현해야합니다.

**Comment by chanyoung** [comment]
구분자를 넣고 키워드 검색으로 구현하면 어떨까요?

**Comment by chanyoung** [comment]
지금 생각해보니 양이 그렇게 많지않은 내선번호 검색인데 하나의 키워드만 지원되도 충분할거 같기도 해요

**Comment by yoonsue** [comment]
- inmem과 mongo로 둘다 구현 완료되었으나, hyucps에 아직 mongo가 설치되지 않음.

- service initalStore를 NewSevice를 생성할때 수행해야할듯하나, path는 bootstrap에 지정되어있어, 어느쪽에 넣어야하나 고민중이다.

**Comment by yoonsue** [comment]
inmem 및 mongo 구현 완료.

현재) 부서명이 완전히 일치해야 내선번호 값이 나옴. 
기능추가사항) 특정 문자열이 포함되는 항목을 모두 출력하도록 만들것.

**Comment by yoonsue** [comment]
내선 번호 검색 기능이 다음과 같이 구현 완료되었습니다.
![image](https://user-images.githubusercontent.com/22068030/46851400-5dab6380-ce32-11e8-8ad2-b84a6871ca8d.png)
이슈 닫겠습니다.

**Comment by yoonsue** [comment]
내선번호 업데이트 및 추가 기능.

**Comment by yoonsue** [comment]
번호로도 검색가능하게 기능 구현
