### ISSUE TITLE
도움말 기능

### ISSUE THREAD

**Issue by chanyoung** [yoonsue/labchat#13]
앞으로 추가될 기능들을 위해서 도움말 기능이 필요해보입니다.

**Comment by chanyoung** [comment]
감사합니다.

**Comment by yoonsue** [comment]
간략하게 도움말 기능을 완성하였습니다.
![image](https://user-images.githubusercontent.com/22068030/46474597-3e9f4700-c81e-11e8-824d-7dc931e994e3.png)

도움말 클릭시의 화면.
![image](https://user-images.githubusercontent.com/22068030/46474611-4bbc3600-c81e-11e8-978a-e74ec0f17e2b.png)

또한, 기타 문맥상 비슷하게 표현되는 문구들에 대해서도 기능이 실행되도록 하였습니다.
추가사항이 더 없다면 이슈 닫겠습니다.

**Comment by chanyoung** [comment]
쓰기 좋아보이네요~
