### ISSUE TITLE
TestScrapMenu always failed on weekends(or holidays)

### ISSUE THREAD

**Issue by chanyoung** [yoonsue/labchat#6]
Since they do not open the cafeteria on weekends or holidays, always retrieves the empty string.

--- FAIL: TestScrapMenu (1.59s)
	service_test.go:30: start with '[중식A]' on url http://www.hanyang.ac.kr/web/www/-254, got ''
	service_test.go:30: start with '[특식]' on url http://www.hanyang.ac.kr/web/www/-255, got ''
	service_test.go:30: start with '[한식]' on url http://www.hanyang.ac.kr/web/www/-258, got ''

**Comment by yoonsue** [comment]
I checked this issue and fix it commit number: 4a8379d77ec77b29a2ed6f130aeb43255ccf4175
As you recommended, the code which got the specific element of given URL was changed into getting whole HTML.
